### ISSUE TITLE
Реализовать взаимодействие с Elastic Service 🐳

### ISSUE THREAD

**Issue by dura0ok** [Concerts-Mate/Users-Service#20]
> Реализовать взаимодействие Users-Service с сервисами Music-Service и Elastic-Service (написать соответствующие сервисы и DTO)

**Comment by dura0ok** [comment]
через grpc

**Comment by dura0ok** [comment]
Срок до 22ого

**Comment by pipichinka** [comment]
> через grpc

это  только для твоего сервиса, да?

**Comment by pipichinka** [comment]
Кирилл победил grpc. ГОЙДА!!!

**Comment by pipichinka** [comment]
Кирилл победил grpc. ГОЙДА!!!
