### ISSUE TITLE
Добавить end-point в Music-Service для валидации ссылок на плейлисты/альбомы 🎛

### ISSUE THREAD

**Issue by dura0ok** [Concerts-Mate/Users-Service#23]

**Comment by llirik42** [comment]
1) Это issue должно было быть в другой репе

**Comment by llirik42** [comment]
Бессмысленное оно (это я вкинул не думая) потому что можно просто сделать запрос на получение информации о плейлисте/альбоме к Music-Service, и если ссылка неправильная, то он об этом сообщит, поэтому можно считать, что задание выполнено)
