### ISSUE TITLE
Проверить какое время возвращает спринг, локальное или UTC +0  🕛❓

### ISSUE THREAD

**Issue by Wooshey1411** [Concerts-Mate/Users-Service#30]
Время концерта может быть передано разными методами, обычно формат UTC. Спринг возвращает дату и время: нужно узнать какое это время.

**Comment by pipichinka** [comment]
Так учимся писать баг рапорты: как ты дёргал? Что ты дёргал? Что именно получал? Желательно со скринами.

**Comment by pipichinka** [comment]
@Wooshey1411

**Comment by Wooshey1411** [comment]
Переотметил. Теперь отвечай на вопрос.

**Comment by llirik42** [comment]
Возвращается время в UTC+7. Сейчас пофикшу так, чтобы время возвращалось локальное для города, в котором концерт
