### ISSUE TITLE
Редактирование протокола API

### ISSUE THREAD

**Issue by Wooshey1411** [Concerts-Mate/Users-Service#36]
Добавить в ответ на запрос POST /user/{id} (добавление пользователя) время создания пользователя при ответе USER_ALREADY_EXIST

Реализовать эндпоинт: GET /cities?lan=A?lon=B для получения списка городов по координатам. Должны быть 2 ответа.
SUCCESS:
{
 "header":....
  "cities": [
      "cityName": ...
    ]
} - список городов возможных. Нужно сделать, чтобы список был упорядоченным, т.е мы ищем в радиусе условно 5 км, и если там будет 2 города - вывести их в порядке близости к центру круга, чем ближе тем лучше.
INVALID_CITY:
{
 "header": ...
} - если в радиусе нет городов.

**Comment by pipichinka** [comment]
будет сделано так:
GET /cities?lan=A?lon=B

{
"status":....
"cities": [
"cityName": ...
]
}

статус равен или Success или InternalError,
соответственно при Success будет возвращаться в поле cities масиив городов, может быть нудевой, если рядом  ничего нет.

**Comment by pipichinka** [comment]
@Wooshey1411
